TASK_COLUMNS = [
    "ACBRNTQT", "AC CERT", "ACFT INT SAFE INSP", "ADAK NAS",
    "Adv Skills Trn", "AFE EQUIP TRNG", "AFE FAM", "AFE FIT CHECK",
    "AFET", "AIR CARD USER TRNG", "AIRCRAFT SERVICE", "AIRCREW FLUSH CERT",
    "AIRLND MSN EVAL", "AIS/IRC INSTR CERT", "AMP-4 CERT", "AMP-4 LANDING",
    "AMP-4 PLT FLYING CERT", "AMP-4 PLT MONITORING", "AMP-4 TAKEOFF",
    "ANTI-HIJACK", "APPROACH CAT II ILS", "APPROACH NONPRECISION",
    "APPROACH PRECISION", "ARLND PHASE 1 QTR", "ARLND PHASE 2 QTR",
    "ARLND PHASE 3 QTR", "ARLND PHASE 4 QTR", "ASSAULT LNDG",
    "CATS-MECOC CERT", "CBRN HANDS-ON", "CMR RECENCY EVENT",
    "COMBAT ON/OFFLOAD", "COMM PROC GT"
]
